[package]
name = "orca"
version = "0.1.0"
authors = ["Luke Whrit <lukewhrit@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
