[package]
name = "orca"
version = "0.1.0"
edition = "2018"
authors = [
    "Luke Whrit <lukewhrit@pm.me>",
    "Jack Dorland <puggo@puggo.space>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
